name: Render Flowcharts

on:
  push: {}
  pull_request: {}

permissions: read-all

concurrency: 
  group: render
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: render
        name: Render
        uses: tbscompany/render-drawio-action@v1.2.2
        with:
          formats: svg
          sub-dirs: "."
          skip-dirs: ".git"
          log-level: info
      - name: List the rendered files
        run: "ls -l ${{ steps.render.outputs.rendered-files }}"
      - name: Tree
        run: tree
        
